package:
  name: pycausal
  version: "1.2.1"
 
source:
  git_rev: v0.1
  git_url: https://github.com/bd2kccd/py-causal.git
 
requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - javabridge
    - numpy
    - pydot
    - pyparsing
    - graphviz
  
about:
  home: https://github.com/bd2kccd/py-causal
  license: LGPL >= 2.1
  license_file: LICENSE